name: 'Setup Drupal action'
author: bluehorndigital
description: 'GitHub Action to setup Drupal for testing an extension'
inputs:
  version:
    description: 'Drupal version constraint'
    required: true
    default: '^9.0'
  path:
    description: 'Path to create the Drupal project'
    required: true
    default: '~/drupal'
  dependencies:
    description: 'Additional dependencies to install'
    required: false
  allow_plugins:
    description: 'Packages to add to allow-plugins for Composer'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'blue'
